### ISSUE TITLE
「メーカー設定」項目が上の項目とくっついて表示される

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/maker-plugin#17]
0.0.2にて確認しました。
商品登録画面にて、アコーディオンとして挿入される「メーカー設定」項目が、
上部のアコーディオン項目とくっついて表示されてしまいます。
（上部のdiv.accordionの中に入ってしまっています）

**Comment by ryo-endo** [comment]
1.0.0でアコーディオンを使用しないように、管理画面のデザインを変更。
それに伴い発生しなくなったので、CLOSEします。
