### ISSUE TITLE
「メーカー設定」項目が表示されない

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/maker-plugin#18]
0.0.2にて確認しました。
商品登録画面にて、置換対象のHTMLの中に「&」などのHTML特殊文字があると、
置換ができずに項目が追加されません。（Maker.phpの197-199行目あたり）
（関連商品プラグインもインストールしていて、商品名に「&」のつくものを登録して起きました。）

**Comment by ryo-endo** [comment]
1.0.0で対応、動作確認ずみ。CLOSEします。
ご報告ありがとうございました。
