### ISSUE TITLE
Entityのネームスペースが間違えてます

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/maker-plugin#20]
ec-cube 3.0.12
プラグイン：Maker　0.0.2

問題：yamlファイルの中にネームスペースが間違えてます
ファイル：app/Plugin/Maker/Resource/doctrine/Plugin.Maker.Entity.MakerPlugin.dcm.yml

対応方法：
行目：１
Plugin\MakerGateway\Entity\MakerPlugin:
↓
Plugin\Maker\Entity\MakerPlugin:

**Comment by ryo-endo** [comment]
1.0.0で対応、動作確認ずみ。CLOSEします。
ご報告ありがとうございました。
